name: Approve PR Sync
on:
  pull_request_target:
    branches:
      - 'sync/int-stats-master'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v3
